apiVersion: v1
kind: Service
metadata:
  name: redis
  labels:
    name: redis-service
    app: voting-app

spec:
  ports:
  - port: 6739
    targetPort: 6739
  selector:
    name: redis-pod
    app: voting-app

      